### ISSUE TITLE
feature/gccontent: gene coordinates

### ISSUE THREAD

**Issue by drisso** [drisso/EDASeq#3]
In the getGeneLengthAndGCContent function, the length and GC content returned are those of the whole gene's region (exons + introns), while we want only the exons.

**Comment by drisso** [comment]
Commit 65be892cbe1ba4c3bfadcbebd9a41c882c8ad407 fixes this for mode biomart.

**Comment by drisso** [comment]
@lgeistlinger do you have time to fix this for mode="org.db"?

**Comment by drisso** [comment]
See 42a906760678b8100f7e2c7f5050d4c8e691bc07. The two modes behave differently. We need to decide on one or the other way. @lgeistlinger any input is appreciated.

**Comment by lgeistlinger** [comment]
Ok, I'm taking care of that. Did I understand it correctly that we want both measures (length and GC content) for a gene only considering its exonic sequence? Alternatively, we could have an additional argument 'seqType' to the function taking values like 'exon', 'intron', 'exon_intron' thus returning exonic, intronic, or exonic and intronic sequence of a gene. Default would be 'exon'. Would that fit your expectations?

**Comment by drisso** [comment]
> Did I understand it correctly that we want both measures (length and GC content) for a gene only considering its exonic sequence?

Yes. That's what's needed by the GC-content normalization implemented in the package. 
If you think it might be useful for other applications, it's fine to have multiple seqType with exon being the default.

In addition, it might be useful to compute length and GC-content for transcripts rather than genes.
That might even be a separate function.

Thanks for your help!

BTW, I broke the code with the 42a906760678b8100f7e2c7f5050d4c8e691bc07 commit, but it could be a step towards what we need. Feel free to start from there or to reset and start from scratch, if you think it's not useful.

**Comment by lgeistlinger** [comment]
Davide, an underlying issue is that the 'biomart' mode is based on ENSEMBL whereas 'org.db' build on the TxDb and BSgenome packages built from UCSC (I was not aware that they differ in gene/transcript annotation but they obviously do).
After discussing that on the Bioc devel mailing list, I have several options to adapt to that depending on what we want:

1. Do we want both modes to behave equally (i.e. consider only the reduced exonic sequence for a gene) *AND* give the same output (i.e. gene length and GC content does not depend on the mode used)

 - it is easy to make them behave equally within the current framework (differences in output are / will be due to the mentioned difference in annotation source)
- it is not as easy to ensure the same output for both modes; this will require an ensembl-based annotation also for the org.db mode and thus a reworking of our current org.db framework
- both modes actually exist because they can differ in output, configuring both modes to give equal output would actually making the biomart mode obsolete for bioc supported organisms (then we can also defunct the biomart mode for these organisms right now) 

2. You mentioned the request for a similar functionality for transcripts - what is the typical use case here and what kind of input IDs I am expected to deal with? Ensembl transcript IDs?

**Comment by drisso** [comment]
Thanks for looking into this.

I think it's fine to have the org.db mode based on UCSC rather than Ensembl. The important thing is that using either annotation, the result is conceptually the same (e.g., the length and GC-content of the gene model defined as the union of all exons of a gene). This should also be clearly explained in the help.

**Comment by drisso** [comment]
Commit 804bbbd319324e2e47c007da1be59720cbb4f6d1 should close this.
